### ISSUE TITLE
Fatal exception on android

### ISSUE THREAD

**Issue by booooza** [rmtmckenzie/flutter_qr_mobile_vision#125]
**Description**: Since the upgrade to version 1.0.0+3 I randomly (?) get fatal exceptions on Android with a complete app crash (see strack trace). Unfortunately I'm not able yet to tell what events cause the issue...

**Affected versions**: 1.0.0+3
**Affected devices**: Nexus 5X API 28 x86 (Emulator), Huawei P20 (Physical)

```
D/AndroidRuntime( 6228): Shutting down VM
E/AndroidRuntime( 6228): FATAL EXCEPTION: main
E/AndroidRuntime( 6228): Process: app, PID: 6228
E/AndroidRuntime( 6228): java.lang.IllegalStateException: Image is already closed
E/AndroidRuntime( 6228): 	at android.media.Image.throwISEIfImageIsInvalid(Image.java:70)
E/AndroidRuntime( 6228): 	at android.media.ImageReader$SurfaceImage.getFormat(ImageReader.java:821)
E/AndroidRuntime( 6228): 	at com.google.firebase.ml.vision.common.FirebaseVisionImage.fromMediaImage(com.google.firebase:firebase-ml-vision@@24.0.1:6)
E/AndroidRuntime( 6228): 	at com.github.rmtmckenzie.qrmobilevision.QrCameraC2$Frame.toImage(QrCameraC2.java:213)
E/AndroidRuntime( 6228): 	at com.github.rmtmckenzie.qrmobilevision.QrDetector.processFrame(QrDetector.java:84)
E/AndroidRuntime( 6228): 	at com.github.rmtmckenzie.qrmobilevision.QrDetector.processLatest(QrDetector.java:79)
E/AndroidRuntime( 6228): 	at com.github.rmtmckenzie.qrmobilevision.QrDetector.onSuccess(QrDetector.java:94)
E/AndroidRuntime( 6228): 	at com.github.rmtmckenzie.qrmobilevision.QrDetector.onSuccess(QrDetector.java:27)
E/AndroidRuntime( 6228): 	at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
E/AndroidRuntime( 6228): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 6228): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6228): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 6228): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 6228): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6228): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 6228): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process ( 6228): Sending signal. PID: 6228 SIG: 9
```

**Comment by lucasbaizer2** [comment]
I have noticed this same exception happening when closing out of the app.

**Comment by rmtmckenzie** [comment]
Ah okay, thanks. Looks like I'm not being careful enough about the image frames, I'll take a look soon!

**Comment by kostasoft** [comment]
This happens on my Nexus 5 when I close the Widget containing QrCamera. Here is the log:

```
04-16 13:43:46.712 218-32136/? E/mm-camera: module_faceproc_port_event_func:886] MCT_EVENT_MODULE_BUF_DIVERT 65539, Cannot start FD, active 10002, frameid 135 135, native 1, mapped 1 1
04-16 13:43:46.798 218-32136/? E/mm-camera: module_faceproc_port_event_func:886] MCT_EVENT_MODULE_BUF_DIVERT 65539, Cannot start FD, active 10002, frameid 136 136, native 1, mapped 1 1
04-16 13:43:46.880 218-32136/? E/mm-camera: module_faceproc_port_event_func:886] MCT_EVENT_MODULE_BUF_DIVERT 65539, Cannot start FD, active 10002, frameid 137 137, native 1, mapped 1 1
04-16 13:43:46.964 218-32136/? E/mm-camera: module_faceproc_port_event_func:886] MCT_EVENT_MODULE_BUF_DIVERT 65539, Cannot start FD, active 10002, frameid 138 138, native 1, mapped 1 1
04-16 13:43:47.020 200-823/? E/mm-camera-intf: mm_camera_poll_thread_del_poll_fd: invalid handler 48896 (0)
04-16 13:43:47.190 200-823/? E/mm-camera-intf: mm_camera_poll_thread_del_poll_fd: invalid handler 49408 (0)
04-16 13:43:47.360 218-32139/? E/mm-camera: isp_unlink_sink_port: E
04-16 13:43:47.360 200-823/? E/QCamera3Channel: virtual qcamera::QCamera3Channel::~QCamera3Channel(): deleting channel 48641
04-16 13:43:47.363 218-32139/? E/mm-camera: isp_unlink_sink_port: E
04-16 13:43:47.363 218-32139/? E/mm-camera-img: faceproc_save_album:774] Error No album 
04-16 13:43:47.363 218-32139/? E/mm-camera-img: faceproc_comp_eng_destroy: Album save failed -1
04-16 13:43:47.364 200-823/? E/QCamera3Channel: virtual qcamera::QCamera3Channel::~QCamera3Channel(): deleting channel 49154
04-16 13:43:47.383 200-823/? E/QCamera3Channel: virtual qcamera::QCamera3Channel::~QCamera3Channel(): deleting channel 48128
04-16 13:43:47.385 218-32139/? E/mm-camera: mct_pipeline_get_stream: no children
04-16 13:43:47.385 218-32139/? E/mm-camera: mct_pipeline_process_set:1451: Couldn't find stream
04-16 13:43:47.465 2686-2694/? E/ANDR-PERF-LOCK: Failed to reset optimization for resource: 4 level: 0
04-16 13:43:47.475 31832-31832/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8cf97001 in tid 31832 (lpsignalflutter)
04-16 13:43:47.580 25323-25323/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-16 13:43:47.580 25323-25323/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys'
04-16 13:43:47.580 25323-25323/? A/DEBUG: Revision: '11'
04-16 13:43:47.580 25323-25323/? A/DEBUG: ABI: 'arm'
04-16 13:43:47.581 25323-25323/? A/DEBUG: pid: 31832, tid: 31832, name: lpsignalflutter  >>> com.kostasoft.helpsignalflutter <<<
04-16 13:43:47.581 25323-25323/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8cf97001
04-16 13:43:47.605 25323-25323/? A/DEBUG:     r0 705cd698  r1 12c796c0  r2 00000000  r3 00000001
04-16 13:43:47.605 25323-25323/? A/DEBUG:     r4 7039b740  r5 8cf97001  r6 ffffffff  r7 00000001
04-16 13:43:47.606 25323-25323/? A/DEBUG:     r8 00000000  r9 b4d36500  sl 12c796c0  fp 00000001
04-16 13:43:47.606 25323-25323/? A/DEBUG:     ip b4d2c140  sp bee66020  lr 7299bc11  pc 729a3860  cpsr 800d0030
04-16 13:43:47.607 25323-25323/? A/DEBUG: backtrace:
04-16 13:43:47.608 25323-25323/? A/DEBUG:     #00 pc 729a3860  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x1ed6000)
04-16 13:43:47.608 25323-25323/? A/DEBUG:     #01 pc 7299bc0d  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x1ed6000)
04-16 13:43:48.303 25323-25323/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_03
04-16 13:43:48.303 25323-25323/? E/DEBUG: AM write failed: Broken pipe
```

**Comment by kostasoft** [comment]
In Flutter Console:
```
W/ImageReader_JNI(20448): ImageReader#close called before Image#close, consider calling Image#close first
I/cgr.qrmv.QrReader(20448): Using new camera API.
I/cgr.qrmv.QrCameraC2(20448): Setting af mode to: 4
I/NDOP    (20448): listening using window listener
W/ImageReader_JNI(20448): ImageReader#close called before Image#close, consider calling Image#close first
F/libc    (20448): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f8e2001 in tid 20448 (lpsignalflutter)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys'
Revision: '11'
ABI: 'arm'
pid: 20448, tid: 20448, name: lpsignalflutter  >>> com.kostasoft.helpsignalflutter <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7f8e2001
    r0 705cd698  r1 12cf5200  r2 00000000  r3 0025cb52
    r4 7039b740  r5 7f8e2001  r6 00000000  r7 00000001
    r8 00000000  r9 b4df6500  sl 12cf5200  fp 00000001
    ip 00000001  sp be811040  lr 7299bc11  pc 729a3860  cpsr 000d0030
backtrace:
    #00 pc 729a3860  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x1ed6000)
    #01 pc 7299bc0d  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x1ed6000)
Tombstone written to: /data/tombstones/tombstone_02
```

**Comment by adriancsbna** [comment]
Same issue on Motorola Moto G5 Plus

**Comment by rohnsht** [comment]
I got the same issue too. I think its with most of the android devices.

**Comment by vinceMuni** [comment]
I tried both on Android and iOS, but it results in a crash only for the former. It usually happens like this:

Open the screen with QR widget -> close it going back -> open again -> close again;

The error is the same as @booooza's.

Thanks for your work

**Comment by rmtmckenzie** [comment]
This should be fixed as of 1.0.1.

**Comment by GabrieleVolpato** [comment]
Hello, I upgraded to version 1.0.1 and the problem persists. This is what i get in Flutter console:

`W/ImageReader_JNI(17996): ImageReader#close called before Image#close, consider calling Image#close first
F/libc    (17996): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f7e502000 in tid 17996 (das.development)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/markw/markw:6.0.1/MMB29M/V10.2.2.0.MBEMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 17996, tid: 17996, name: das.development  >>> come.example.app <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7f7e502000
    x0   0000007f7e502000  x1   0000000000000000  x2   0000000000000000  x3   0000000000020000
    x4   00000000702493f0  x5   0000007f9e0a17c8  x6   4d591d44dff72fd8  x7   000000007112d170
    x8   0000007fc1d61ec0  x9   0000000000000000  x10  000000006faef8a8  x11  000000006faef8b0
    x12  0000000000000000  x13  0000000000004977  x14  00000000710be1a8  x15  0000000000001ea5
    x16  0000000000000000  x17  000000007024a15c  x18  000000559dce0ea0  x19  0000000012d575c0
    x20  0000000000000000  x21  0000000012d14e60  x22  0000000000000000  x23  0000000000000000
    x24  000000007067aa08  x25  000027920000464c  x26  000027920000464c  x27  0000000012dc1b80
    x28  0000000071730bac  x29  0000007fc1d642b8  x30  00000000731e6174
    sp   0000007fc1d63e70  pc   00000000731f1150  pstate 0000000080000000
backtrace:
    #00 pc 00000000731f1150  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x2564000)
    #01 pc 00000000731e6170  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x2564000)
Tombstone written to: /data/tombstones/tombstone_02
Lost connection to device.
`

**Comment by fabirt** [comment]
Hello, I'm using the version 1.0.1+1 and still have the same issue on Android Samsung J7

**Comment by Xaeroxaero** [comment]
Its also still occuring for me - Lenovo Tab10 PLUS. Also I have the same issue when lunching on android emulator with 6.0

**Comment by taroooth** [comment]
I might have been able to avoid this problem.
```
 ImageReader # close called before Image # close, consider calling Image # close first"
```
The logs like above have been output, so if I stopped the camera before closing the camera, I avoided the crash in my environment. 

```
await QrMobileVision.stop();
```

```
QrCamera(
     onError: (context, error) => Text(
       error.toString(),
       style: const TextStyle(color: Colors.red),
     ),
     qrCodeCallback: (code) async {
        await QrMobileVision.stop();
        Navigator.of(context).pop();
     },
 );
```
Please try it. Thank you!
