### ISSUE TITLE
Create an example scanner overlay

### ISSUE THREAD

**Issue by jaumard** [rmtmckenzie/flutter_qr_mobile_vision#24]
Would be nice to have a default scanner skin overlay and a parameter to override it put everything we want on top of the camera preview

**Comment by jaumard** [comment]
I tried to implement it on my app but didn't manage to do it: 
```
Stack(
                        alignment: FractionalOffset.center,
                        fit: StackFit.expand,
                        children: <Widget>[
                          QrCamera(
                            notStartedBuilder: (context) => PlatformCircularProgressIndicator(),
                            qrCodeCallback: (code) {},
                          ),
                          Container(width:300.0,height:300.0,decoration: BoxDecoration(color: Color(0xFF00000)),),
                        ],
                      ),
```
I know the overlay is not correct but I don't even see the black square on top of the preview :/
Any ideas ?

**Comment by rmtmckenzie** [comment]
As much as a default skin could be nice, I don't think it's really suited to this plugin as it supports barcodes & qr codes of many different shapes - what might work for you may not work for someone else.

The reason it's not showing up is going to make you groan though, you're missing a 0 in your colour definition, which should really be an error but flutter's just ignoring it instead =D.

**Comment by rmtmckenzie** [comment]
If I get time I could maybe make a more elaborate example with a crosshair for the example...

**Comment by rmtmckenzie** [comment]
I caved slightly and made a child parameter in the newest revision. If you pass a child in, it will size to the same as the image. The example now has an orange border. See v0.0.5 once it's done processing.

**Comment by jaumard** [comment]
So here is the result of what I have implemented into my app, let me know if you want me to do a PR with it or not :)
<img width="430" alt="capture d ecran 2018-07-20 a 12 14 08" src="https://user-images.githubusercontent.com/2970449/42997290-73fad804-8c16-11e8-8481-e196fa862b52.png">

**Comment by rmtmckenzie** [comment]
If you'd like you could do a PR to add this to the example app. However, I still don't think it would be a good idea to put it right in to the plugin as it really mostly makes sense for a QR Code. The app I'm using this plugin in for example has a different UI for which that wouldn't work very well.

**Comment by dadja** [comment]
> Colors and border size are configurable :)

hello sir is it possible that you share the code which you produce to attempt that i am trying to do so too.Thanks

**Comment by jaumard** [comment]
Sure :) 
```

class _ScannerOverlayShape extends ShapeBorder {
  final Color borderColor;
  final double borderWidth;
  final Color overlayColor;

  _ScannerOverlayShape({
    this.borderColor = Colors.white,
    this.borderWidth = 1.0,
    this.overlayColor = const Color(0x88000000),
  });

  @override
  EdgeInsetsGeometry get dimensions => EdgeInsets.all(10.0);

  @override
  Path getInnerPath(Rect rect, {TextDirection textDirection}) {
    return Path()
      ..fillType = PathFillType.evenOdd
      ..addPath(getOuterPath(rect), Offset.zero);
  }

  @override
  Path getOuterPath(Rect rect, {TextDirection textDirection}) {
    Path _getLeftTopPath(Rect rect) {
      return Path()
        ..moveTo(rect.left, rect.bottom)
        ..lineTo(rect.left, rect.top)
        ..lineTo(rect.right, rect.top);
    }

    return _getLeftTopPath(rect)
      ..lineTo(
        rect.right,
        rect.bottom,
      )
      ..lineTo(
        rect.left,
        rect.bottom,
      )
      ..lineTo(
        rect.left,
        rect.top,
      );
  }

  @override
  void paint(Canvas canvas, Rect rect, {TextDirection textDirection}) {
    const lineSize = 30;

    final width = rect.width;
    final borderWidthSize = width * 10 / 100;
    final height = rect.height;
    final borderHeightSize = height - (width - borderWidthSize);
    final borderSize = Size(borderWidthSize / 2, borderHeightSize / 2);

    var paint = Paint()
      ..color = overlayColor
      ..style = PaintingStyle.fill;

    canvas
      ..drawRect(
        Rect.fromLTRB(rect.left, rect.top, rect.right, borderSize.height + rect.top),
        paint,
      )
      ..drawRect(
        Rect.fromLTRB(rect.left, rect.bottom - borderSize.height, rect.right, rect.bottom),
        paint,
      )
      ..drawRect(
        Rect.fromLTRB(rect.left, rect.top + borderSize.height, rect.left + borderSize.width, rect.bottom - borderSize.height),
        paint,
      )
      ..drawRect(
        Rect.fromLTRB(rect.right - borderSize.width, rect.top + borderSize.height, rect.right, rect.bottom - borderSize.height),
        paint,
      );

    paint = Paint()
      ..color = borderColor
      ..style = PaintingStyle.stroke
      ..strokeWidth = borderWidth;

    final borderOffset = borderWidth / 2;
    final realReact = Rect.fromLTRB(borderSize.width + borderOffset, borderSize.height + borderOffset + rect.top, width - borderSize.width - borderOffset,
        height - borderSize.height - borderOffset + rect.top);

    //Draw top right corner
    canvas
      ..drawPath(
          Path()
            ..moveTo(realReact.right, realReact.top)
            ..lineTo(realReact.right, realReact.top + lineSize),
          paint)
      ..drawPath(
          Path()
            ..moveTo(realReact.right, realReact.top)
            ..lineTo(realReact.right - lineSize, realReact.top),
          paint)
      ..drawPoints(
        PointMode.points,
        [Offset(realReact.right, realReact.top)],
        paint,
      )

      //Draw top left corner
      ..drawPath(
          Path()
            ..moveTo(realReact.left, realReact.top)
            ..lineTo(realReact.left, realReact.top + lineSize),
          paint)
      ..drawPath(
          Path()
            ..moveTo(realReact.left, realReact.top)
            ..lineTo(realReact.left + lineSize, realReact.top),
          paint)
      ..drawPoints(
        PointMode.points,
        [Offset(realReact.left, realReact.top)],
        paint,
      )

      //Draw bottom right corner
      ..drawPath(
          Path()
            ..moveTo(realReact.right, realReact.bottom)
            ..lineTo(realReact.right, realReact.bottom - lineSize),
          paint)
      ..drawPath(
          Path()
            ..moveTo(realReact.right, realReact.bottom)
            ..lineTo(realReact.right - lineSize, realReact.bottom),
          paint)
      ..drawPoints(
        PointMode.points,
        [Offset(realReact.right, realReact.bottom)],
        paint,
      )

      //Draw bottom left corner
      ..drawPath(
          Path()
            ..moveTo(realReact.left, realReact.bottom)
            ..lineTo(realReact.left, realReact.bottom - lineSize),
          paint)
      ..drawPath(
          Path()
            ..moveTo(realReact.left, realReact.bottom)
            ..lineTo(realReact.left + lineSize, realReact.bottom),
          paint)
      ..drawPoints(
        PointMode.points,
        [Offset(realReact.left, realReact.bottom)],
        paint,
      );
  }

  @override
  ShapeBorder scale(double t) {
    return _ScannerOverlayShape(
      borderColor: borderColor,
      borderWidth: borderWidth,
      overlayColor: overlayColor,
    );
  }
}
```

Usage: 
```
Container(
          decoration: ShapeDecoration(
            shape: _ScannerOverlayShape(
              borderColor: Colors.red,
              borderWidth: 3.0,
            ),
          ),
        ),
```

**Comment by mrkhanhkhi** [comment]
> Colors and border size are configurable :)

Hi @jaumard ,
Thank you very much for your impressive work,  can you tell me how to move the position of the shape?

**Comment by jaumard** [comment]
Hi, This has been written to target the center of the widget, if you want another position you'll have to change most of the code unfortunately because the first part draw the background (black transparent background except in the center) the second part is drawing the colorful corners. If you want to change the position you'll have to change all the `Rect.fromLTRB ` and `moveTo ` `lineTo` play with it until you manage to get what you want

**Comment by mrkhanhkhi** [comment]
Oh, I see, thank  you so much, will give it a try.

**Comment by TBoonkwan** [comment]
@jaumard  How can i need to fix size the frame overlay. thank in advance

**Comment by TBoonkwan** [comment]
I need to specific target the center and size = 200
